### ISSUE TITLE
Clicking on Download on people search results gives an error   

### ISSUE THREAD

**Issue by anusharanganathan** [culturesofknowledge/emlo-project#184]
The URL

http://emlo-edit.cottagelabs.com/person/search?csrfmiddlewaretoken=UkR2Ocz5d5I2BVlqOgzCtwUoVrGGsh98H8iD3cgzcqAxqU5FbvwrflrJCGs7hphm&recref_mode=0&foaf_name_lookup=contains&foaf_name=&birth_year_from=&birth_year_to=&death_year_from=&death_year_to=&flourished_year_from=&flourished_year_to=&gender=&person_or_group=&sent_lookup=equals&sent=&recd_lookup=equals&recd=&all_works_lookup=equals&all_works=&mentioned_lookup=equals&mentioned=&roles_lookup=contains&roles=&editors_notes_lookup=contains&editors_notes=&further_reading_lookup=contains&further_reading=&images_lookup=contains&images=&other_details_lookup=contains&other_details=&change_timestamp_from=&change_timestamp_to=&change_user_lookup=contains&change_user=&iperson_id_lookup=equals&iperson_id=&order=asc&sort_by=foaf_name&num_record=100&page=2&__form_action=download_csv

Stack trace

```
Environment:


Request Method: GET
Request URL: http://localhost:8000/person/search?csrfmiddlewaretoken=UkR2Ocz5d5I2BVlqOgzCtwUoVrGGsh98H8iD3cgzcqAxqU5FbvwrflrJCGs7hphm&recref_mode=0&foaf_name_lookup=contains&foaf_name=&birth_year_from=&birth_year_to=&death_year_from=&death_year_to=&flourished_year_from=&flourished_year_to=&gender=&person_or_group=&sent_lookup=equals&sent=&recd_lookup=equals&recd=&all_works_lookup=equals&all_works=&mentioned_lookup=equals&mentioned=&roles_lookup=contains&roles=&editors_notes_lookup=contains&editors_notes=&further_reading_lookup=contains&further_reading=&images_lookup=contains&images=&other_details_lookup=contains&other_details=&change_timestamp_from=&change_timestamp_to=&change_user_lookup=contains&change_user=&iperson_id_lookup=equals&iperson_id=&order=asc&sort_by=foaf_name&num_record=100&page=2&__form_action=download_csv

Django Version: 4.0.6
Python Version: 3.10.6
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'sass_processor',
 'core',
 'login',
 'uploader',
 'location',
 'work',
 'institution',
 'manifestation',
 'person',
 'publication',
 'audit',
 'list']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)

The above exception (insufficient data in "D" message
lost synchronization with server: got message type "0", length 1
) was the direct cause of the following exception:
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/code/core/helper/view_utils.py", line 286, in get
    return resp_fn(request, *args, **kwargs)
  File "/code/core/helper/view_utils.py", line 277, in resp_download_csv
    return super().get(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
  File "/code/core/helper/view_utils.py", line 204, in get_context_data
    context = super().get_context_data(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/list.py", line 128, in get_context_data
    paginator, page, queryset, is_paginated = self.paginate_queryset(
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/list.py", line 73, in paginate_queryset
    page = paginator.page(page_number)
  File "/usr/local/lib/python3.10/site-packages/django/core/paginator.py", line 75, in page
    number = self.validate_number(number)
  File "/usr/local/lib/python3.10/site-packages/django/core/paginator.py", line 53, in validate_number
    if number > self.num_pages:
  File "/usr/local/lib/python3.10/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.10/site-packages/django/core/paginator.py", line 102, in num_pages
    if self.count == 0 and not self.allow_empty_first_page:
  File "/usr/local/lib/python3.10/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.10/site-packages/django/core/paginator.py", line 96, in count
    return c()
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 470, in count
    return self.query.get_count(using=self.db)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 552, in get_count
    number = obj.get_aggregation(using, ["__count"])["__count"]
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 537, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1361, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)

Exception Type: OperationalError at /person/search
Exception Value: insufficient data in "D" message
lost synchronization with server: got message type "0", length 1

```

**Comment by J4bbi** [comment]
Aside from the fact that the download search functionality isn't properly working, this seems like a very strange bug.

When I tried recreating the error I got a different error:

A `ValueError` is a very different beast from the `OperationalError`

```

ValueError at /person/search
invalid literal for int() with base 10: 'cofk_import_comenius2-recipient:000000581'
Request Method:	GET
Request URL:	http://localhost:8000/person/search?csrfmiddlewaretoken=uTpyN5cHaJoqTZxIPKcdcF8Sl9NBIxk3S9aYlpLgHDBjVAKJF4mY8enbCm3Qflb6&recref_mode=0&foaf_name_lookup=contains&foaf_name=&birth_year_from=1500&birth_year_to=&death_year_from=&death_year_to=&flourished_year_from=&flourished_year_to=&gender=&person_or_group=&sent_lookup=equals&sent=&recd_lookup=equals&recd=&all_works_lookup=equals&all_works=&mentioned_lookup=equals&mentioned=&roles_lookup=contains&roles=&editors_notes_lookup=contains&editors_notes=&further_reading_lookup=contains&further_reading=&images_lookup=contains&images=&other_details_lookup=contains&other_details=&change_timestamp_from=&change_timestamp_to=&change_user_lookup=contains&change_user=&iperson_id_lookup=equals&iperson_id=&order=asc&sort_by=gender&num_record=100&page=7&__form_action=download_csv
Django Version:	4.0.6
Exception Type:	ValueError
Exception Value:	
invalid literal for int() with base 10: 'cofk_import_comenius2-recipient:000000581'
Exception Location:	/usr/local/lib/python3.10/site-packages/django/db/models/expressions.py, line 351, in <lambda>
Python Executable:	/usr/local/bin/python
Python Version:	3.10.7
Python Path:	
['/code',
 '/usr/local/lib/python310.zip',
 '/usr/local/lib/python3.10',
 '/usr/local/lib/python3.10/lib-dynload',
 '/usr/local/lib/python3.10/site-packages']
Server time:	Fri, 03 Mar 2023 12:48:41 +0000
Traceback Switch to copy-and-paste view
/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py, line 55, in inner
                response = get_response(request) …
Local vars
/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py, line 197, in _get_response
                response = wrapped_callback(request, *callback_args, **callback_kwargs) …
Local vars
/usr/local/lib/python3.10/site-packages/django/views/generic/base.py, line 84, in view
            return self.dispatch(request, *args, **kwargs) …
Local vars
/usr/local/lib/python3.10/site-packages/django/contrib/auth/mixins.py, line 73, in dispatch
        return super().dispatch(request, *args, **kwargs) …
Local vars
/usr/local/lib/python3.10/site-packages/django/views/generic/base.py, line 119, in dispatch
        return handler(request, *args, **kwargs) …
Local vars
/code/core/helper/view_utils.py, line 286, in get
            return resp_fn(request, *args, **kwargs) …
Local vars
/code/core/helper/view_utils.py, line 277, in resp_download_csv
        return super().get(request, *args, **kwargs) …
Local vars
/usr/local/lib/python3.10/site-packages/django/views/generic/list.py, line 174, in get
        context = self.get_context_data() …
Local vars
Variable	Value
allow_empty	
True
args	
()
kwargs	
{}
request	
<WSGIRequest: GET '/person/search?csrfmiddlewaretoken=uTpyN5cHaJoqTZxIPKcdcF8Sl9NBIxk3S9aYlpLgHDBjVAKJF4mY8enbCm3Qflb6&recref_mode=0&foaf_name_lookup=contains&foaf_name=&birth_year_from=1500&birth_year_to=&death_year_from=&death_year_to=&flourished_year_from=&flourished_year_to=&gender=&person_or_group=&sent_lookup=equals&sent=&recd_lookup=equals&recd=&all_works_lookup=equals&all_works=&mentioned_lookup=equals&mentioned=&roles_lookup=contains&roles=&editors_notes_lookup=contains&editors_notes=&further_reading_lookup=contains&further_reading=&images_lookup=contains&images=&other_details_lookup=contains&other_details=&change_timestamp_from=&change_timestamp_to=&change_user_lookup=contains&change_user=&iperson_id_lookup=equals&iperson_id=&order=asc&sort_by=gender&num_record=100&page=7&__form_action=download_csv'>
self	
<person.views.PersonSearchView object at 0x7fe9f3fd3b80>
```

@philipkcl , any ideas?

**Comment by philipkcl** [comment]
should be solved
